<?php if (isset($products)): ?>
    <table class='p_cont doc_info prod_top' >
        <thead class='p_cont th doc_info prod_top'>
        <th class="col1">Товар</th>
        <th class="sub1col2 acenter">К-во</th>
        <th class="sub2col2 acenter">Цена</th> 
        <?php if ($debit == '0,00'): ?>
            <th class="col3">&nbsp;</th> 
            <th class="col4">Всего :</th> 
        <?php else: ?>
            <th class="col3">Всего :</th> 
            <th class="col4">&nbsp;</th> 
        <?php endif ?>
        <th class="col5">
            <?php if ($declar == '1'): ?>
                № Декларации
            <?php else: ?>
                &nbsp;
            <?php endif ?>
        </th>
    </thead>
    <tbody>
        <?php foreach ($products as $prod): ?>
            <tr>
                <td class="col1  small">
                    <span class="showplus">&nbsp;</span>
                    <span class="showspan">*</span>
                    <?php echo $prod->Product; ?>
                </td>
                <td class="sub1col2 acenter">
                    <?php echo $prod->Quantity; ?>
                </td>
                <td class="sub2col2 acenter">
                    <?php echo $prod->Price; ?>
                </td>
                <?php if ($debit == '0,00'): ?>
                    <td class="col3 acenter">&nbsp;</td> 
                    <td class="col4 acenter"><?php echo $prod->Cost; ?></td>
                <?php else: ?>
                    <td class="col3 acenter"><?php echo $prod->Cost; ?></td> 
                    <td class="col4 acenter">&nbsp;</td>
                <?php endif ?>
                <td class="col5 acenter">
                    <?php if ($declar == '1'): ?>
                        <?php if (isset($prod->Declaration)): ?>
                            <?php echo $prod->Declaration ?>
                        <?php else: ?>
                            декларация не найдена
                        <?php endif ?>
                    <?php else: ?>
                        &nbsp;
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach; ?>
    <tbody>
    </table>
<?php endif ?>

