<div id="trade">
    <div id="pagetitle">Поступления</div>
    <?php foreach ($receipts as $ti => $item): ?>
        <table id="firstdiv" class='contract_info' declar="<?php echo $item->WithDeclaration ?>">   
            <thead class='p_cont th'>
                <tr>
                    <th class="col1">Договор</th>
                    <th colspan="2" class="col2">&nbsp;</th> 
                    <th class="col3">Сумма</th> 
                    <th class="col4">&nbsp;</th> 
                    <th class="col5">&nbsp;</th> 
                </tr>
            </thead>
            <tbody class='p_cont'> 
                <tr>
                    <td class="col1 colcontr small">
                        <span class="showplus showdate" ti="<?= $ti ?>">+</span>
                        <?php echo $item->NameContract . " (" . $item->NameContract . ")"; ?>
                    </td>
                    <td colspan="2" class="col2 acenter">&nbsp;</td> 
                    <td class="col3 acenter"><?php echo $item->Cost; ?></td> 
                    <td class="col4 acenter">&nbsp;</td> 
                    <td class="col5 acenter">&nbsp;</td> 
                </tr>
                <tr class = "hideblock" ti="<?= $ti ?>">
                    <td colspan="6">
                        <?php if (isset($item->Row)): ?>
                            <?php foreach ($item->Row as $dt => $date): ?>
                                <table class='p_cont date_info'>
                                    <tbody>
                                        <tr>
                                            <td class="col1 small">
                                                <span class="showplus showdoc" dt="<?= $dt ?>">+</span>
                                                <?php echo $date->Date; ?>
                                            </td>
                                            <td colspan="2" class="col2 acenter">&nbsp;</td> 
                                            <td class="col3 acenter"><?php echo $date->Cost; ?></td> 
                                            <td class="col4 acenter">&nbsp;</td> 
                                            <td class="col5 acenter">&nbsp;</td>
                                        </tr>
                                        <tr class="hideblock" dt="<?= $dt ?>">
                                            <td colspan="6">
                                                <?php if (isset($date->Row)): ?>
                                                    <table class='p_cont  doc_info'>
                                                        <thead class='p_cont th doc_info'>
                                                        <th class="col1">№ Документа</th>
                                                        <th colspan="2" class="col2">Валюта</th> 
                                                        <th class="col3">Сума</th> 
                                                        <th class="col4">&nbsp;</th> 
                                                        <th class="col5">Основание</th> 
                                                        </thead>
                                                        <tbody class='p_cont doc_info'>
                                                            <?php foreach ($date->Row as $dc => $doc): ?>
                                                                <tr>
                                                                    <td class="col1 small">
                                                                        <span class="showplus showprod" dc="<?= $dc ?>" value = '<?= $doc->IDDocument ?>'>+</span>
                                                                        <?php echo $doc->NumberDocument; ?>
                                                                    </td>
                                                                    <td colspan="2" class="col2 acenter"><?php echo $doc->Currency; ?></td> 
                                                                    <td class="col3  acenter"><?php echo $doc->Cost; ?></td> 
                                                                    <td class="col4  acenter">&nbsp;</td> 
                                                                    <td class="col5 acenter"><?php echo $doc->Basis; ?></td>
                                                                </tr>
                                                                <tr class="hideblock mblock" dc="<?= $dc ?>">
                                                                    <td colspan="6">
                                                                        <div class="mblock">
                                                                            информация загружается...
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                            <?php endforeach ?>
                                                        </tbody>
                                                    </table>
                                                <?php endif ?>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            <?php endforeach ?> 

                        <?php endif ?>
                    </td>
                </tr>
            </tbody>
        </table>
    <?php endforeach ?>

</div>
<script>

    $(".showdate").click(function () {
        var ti = $(this).attr("ti");
        $(this).closest("tbody").find("tr[ti=" + ti + "]").toggle(300);
        if ($(this).html() == "+") {
            $(this).html("-");
        } else {
            $(this).html("+");
        }

    });
    $(".showdoc").click(function () {
        var dt = $(this).attr("dt");
        $(this).closest("tbody").find("tr[dt=" + dt + "]").toggle(300);
        if ($(this).html() == "+")
            $(this).html("-");
        else
            $(this).html("+");

    });
    $(".showprod").click(function () {

        var dc = $(this).attr("dc");
        var docId = $(this).attr("value");

        if ($(this).hasClass('downloaded')) {
            $(this).closest("tbody").find("tr[dc=" + dc + "]").toggle(300);
        } else {

            var debit = $(this).closest("tbody").find("col3").text();
            var declar = $('#firstdiv').attr("declar");
            var tag = $(this).closest("tbody").find("tr[dc=" + dc + "]");

            getProducts(docId, tag, debit, declar);

            $(this).addClass('downloaded');
            $(this).closest("tbody").find("tr[dc=" + dc + "]").toggle(300);
        }

        if ($(this).html() == "+")
            $(this).html("-");
        else
            $(this).html("+");

    });
</script>


