<div id="trade">
    <div id="pagetitle">Взаиморасчеты</div>
    <?php foreach ($trade as $ti => $item): ?>
    <div id="firstdiv" class='contract_info' declar="<?php echo $item->WithDeclaration?>">   
            <div class='p_cont th'>
                <div class="col1">Договор</div>
                <div class="col2">Начальный остаток</div> 
                <div class="col3">Приход</div> 
                <div class="col4">Расход</div> 
                <div class="col5">Конечный остаток</div> 
            </div>
            <div class='p_cont'>                
                <div class="col1 small">
                    <span class="showplus showdate" ti="<?= $ti ?>">+</span>
                    <?php echo $item->NameContract . " (" . $item->Currency . ")"; ?>
                </div>
                <div class="col2 acenter"><?php echo $item->TradeLiabilityBegin; ?></div> 
                <div class="col3 acenter"><?php echo $item->TradeLiabilityDebit; ?></div> 
                <div class="col4 acenter"><?php echo $item->TradeLiabilityCredit; ?></div> 
                <div class="col5 acenter"><?php echo $item->TradeLiabilityEnd; ?></div> 


                <div class="hideblock" ti="<?= $ti ?>">
                    <?php if (isset($item->Rows)): ?>
                        <?php foreach ($item->Rows->Row as $dt => $date): ?>
                            <div class='p_cont date_info'>
                                <div class="col1 small">
                                    <span class="showplus showdoc" dt="<?= $dt ?>">+</span>
                                    <?php echo $date->Date; ?>
                                </div>
                                <div class="col2 acenter"><?php echo $date->TradeLiabilityBegin; ?></div> 
                                <div class="col3 acenter"><?php echo $date->TradeLiabilityDebit; ?></div> 
                                <div class="col4 acenter"><?php echo $date->TradeLiabilityCredit; ?></div> 
                                <div class="col5 acenter"><?php echo $date->TradeLiabilityEnd; ?></div> 
                                <div class="hideblock" dt="<?= $dt ?>">
                                    <?php if (isset($date->Rows->Row)): ?>
                                        <div class='p_cont th doc_info' >
                                            <div class="col1">Документ</div>
                                            <div class="col2">&nbsp;</div> 
                                            <div class="col3">Приход</div> 
                                            <div class="col4">Расход</div> 
                                            <div class="col5">&nbsp;</div> 
                                        </div>
                                        <?php foreach ($date->Rows->Row as $dc => $doc): ?>
                                            <div class='p_cont doc_info'>
                                                <div class="col1 small">
                                                    <?php if ($doc->AvailableProducts == '1') : ?>  
                                                        <span class="showplus showprod" dc="<?= $dc ?>" value = '<?= $doc->IDDocument ?>'>+</span>
                                                    <?php else: ?>
                                                        <span class="showplus" >&nbsp;</span>
                                                    <?php endif ?> 
                                                    <?php echo $doc->NameDocument; ?>
                                                </div>
                                                <div class="col2 acenter">&nbsp;</div> 
                                                <div class="col3 acenter"><?php echo $doc->TradeLiabilityDebit; ?></div> 
                                                <div class="col4 acenter"><?php echo $doc->TradeLiabilityCredit; ?></div> 
                                                <div class="col5 acenter">&nbsp;</div>


                                                <div class="hideblock mblock" dc="<?= $dc ?>">
                                                информация загружается...
                                                </div>

                                            </div>
                                        <?php endforeach ?>                        
                                    <?php endif ?>
                                </div>
                            </div>
                        <?php endforeach ?> 
                    </div>
                <?php endif ?>
            </div>
        </div>
    <?php endforeach ?>

</div>
<script>
    $(".showdate").click(function () {
        var ti = $(this).attr("ti");

        $(this).parent().parent().children("div[ti=" + ti + "]").toggle(300);
        if ($(this).html() == "+") {
            $(this).html("-");
        } else {
            $(this).html("+");
        }
    });
    $(".showdoc").click(function () {
        var dt = $(this).attr("dt");
        $(this).parent().parent().children("div[dt=" + dt + "]").toggle(300);
        if ($(this).html() == "+")
            $(this).html("-");
        else
            $(this).html("+");
    });
    $(".showprod").click(function () {

        var dc = $(this).attr("dc");
        var docId = $(this).attr("value");

        if ($(this).hasClass('downloaded')) {
            $(this).parent().parent().children("div[dc=" + dc + "]").toggle(300);
        } else {

            var debit = $(this).parent().parent().children("div.col3").text();
            var declar = $('#firstdiv').attr("declar");
            var tag = $(this).parent().parent().children("div[dc=" + dc + "]");

            getProducts(docId, tag, debit, declar);

            $(this).addClass('downloaded');
            $(this).parent().parent().children("div[dc=" + dc + "]").toggle(300);
        }

        if ($(this).html() == "+")
            $(this).html("-");
        else
            $(this).html("+");



    });
</script>