<div class="container">
    <div class="jumbotron auth">
        <div class="container">
            <?php if ($this->error): ?>
                <p class="error">
                    Введенные данные не валидны (проверьте Ваши данные.)
                </p>
            <?php endif ?>
            <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', '/customers/login/process');
            $form->setAttribute('method', 'post');
            echo $this->form()->openTag($form);
            ?>
            <div class="zend_form input-group">
                <div class="row">
                    <p><?php echo $this->formLabel($form->get('login')) ?></p>
                    <p><?php echo $this->formElement($form->get('login')) ?> </p>           
                    <p><?php echo $this->formElementErrors($form->get('login')) ?></p>
                </div>            
                <div class="row">
                    <p><?php echo $this->formLabel($form->get('pass')) ?></p>
                    <p><?php echo $this->formElement($form->get('pass')) ?> </p>           
                    <p><?php echo $this->formElementErrors($form->get('pass')) ?></p>
                </div>            
                <div class="row">
                    <p><?php echo $this->formButton($form->get('submit')) ?></p>           
                </div>            

            </div>
            <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
</div>


